// Angular/StudentApp/src/app/components/student-card/student-card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Student } from '../../models/student.model';

// Presentational component — receives data via @Input(), emits events via
// @Output(). This is Angular's equivalent of React props + callback props.
@Component({
  selector: 'app-student-card',
  standalone: true,
  imports: [],
  templateUrl: './student-card.component.html',
  styleUrl: './student-card.component.css',
})
export class StudentCardComponent {
  @Input({ required: true }) student!: Student;
  @Output() delete = new EventEmitter<number>();

  get gradeColor(): string {
    switch (this.student.grade) {
      case 'A':
        return '#27ae60';
      case 'B':
        return '#f39c12';
      default:
        return '#e74c3c';
    }
  }

  onDeleteClick(): void {
    this.delete.emit(this.student.id);
  }
}

<div class="student-card">
  <div class="card-info">
    <h3>{{ student.name }}</h3>
    <p>Course: <strong>{{ student.course }}</strong></p>
    <p>Grade: <strong [style.color]="gradeColor">{{ student.grade }}</strong></p>
  </div>
  <button class="btn-delete" (click)="onDeleteClick()">Delete</button>
</div>

// React/Exercise1_StudentApp/src/components/StudentCard.jsx
// Functional component — receives props from StudentList
const StudentCard = ({ student, onDelete }) => {
  // ES6 destructuring of props
  const { id, name, course, grade } = student;

  const gradeColor = grade === 'A' ? '#27ae60' : grade === 'B' ? '#f39c12' : '#e74c3c';

  return (
    <div className="student-card">
      <div className="card-info">
        <h3>{name}</h3>
        <p>Course: <strong>{course}</strong></p>
        <p>Grade: <strong style={{ color: gradeColor }}>{grade}</strong></p>
      </div>
      <button className="btn-delete" onClick={() => onDelete(id)}>
        Delete
      </button>
    </div>
  );
};

export default StudentCard;
